# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'AMS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AMS
	pod 'AnimatedGradientView'
	pod 'Eureka'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'
	pod 'Firebase/Storage'
 

  target 'AMSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AMSUITests' do
    # Pods for testing
  end

end

